<?php

/* * ***** ****** ****** ****** ****** ******

 * Page         :
 * Description  :   Helper functions for creating %HTML Forms
 * Last Updated :
 *
 * ****** ****** ****** ****** ****** ***** */

/**
 * @file
 * \brief Helper functions to create %HTML Forms
 * 
 * @author Shafiul Azam
 */


/**
 * Generate %HTML single-line text input field
 * @param string $value - value to appear in the field
 * @param array $attributes - key-value pair of attributes. Key is attribute name & value is value for that attribute.
 * @return string -  output %HTML 
 * 
 * \code
 * // For Example, 
 * form_input('hello', array('class' => 'myClass', 'id' => 'myTextInput')) 
 * // will produce:
 * <input type="text" value= "hello" class="myClass" id="myTextInput" name="*AutomaticallyGenerated-Don't Worry of it!*"  />
 * \endcode
 */
function form_input($value='', $attributes=null) {
    return array('input', array(
        'text', $value, $attributes
    ));
}


/**
 * Generate %HTML password input field
 * @param string $value - value to appear in the field
 * @param array $attributes - key-value pair of attributes. Key is attribute name & value is value for that attribute.
 * @return string -  output %HTML 
 */
function form_password($value='', $attributes=null) {
    return array('input', array(
        'password', $value, $attributes
    ));
}

/**
 * Generate %HTML multiline text input (textarea) field
 * @param string $value - value to appear in the field
 * @param array $attributes - key-value pair of attributes. Key is attribute name & value is value for that attribute.
 * @return string -  output %HTML 
 */
function form_textarea($value='', $attributes=null) {
    return array('textarea', array(
        $attributes, $value
    ));
}

/**
 * Generate %HTML drop-down (select) field
 * @param $options - a key-value pair array for constructing the options for the  dropdown list. 
 * @param mixed $value - value to appear as selected in the list. For single value, use string, for multiple items to be selected, use array.
 * @param array $attributes - key-value pair of attributes. Key is attribute name & value is value for that attribute.
 * @return string -  output %HTML 
 * 
 * \code
 * // For example, Following Code:
        form_dropdown(array(
            "male" => "Male",
            "female" => "Female"
        );, 'female');
  // Will Produce:
 <select  name = '*AUTOGENERATED*'><option  name = 'male' value = 'male'>Male</option><option selected = 'selected' name = 'female' value = 'female'>Female</option></select>

 * \endcode
 */
function form_dropdown($options,$value=null, $attributes=null) {
    return array('select', array(
        $options, $value, $attributes
    ));
}



?>